mod error;
use error::AppError;

mod wc;

fn main() {
    todo!()
}
